# Generated by Django 6.0 on 2026-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
